import React, { useEffect, useState } from "react";
import styles from "../styles/blog.module.css";
import Head from "next/head";
import Link from "next/link";

const Blog = () => {
  const [blogs, setBlogs] = useState([]);

  useEffect(() => {
    fetch("http://localhost:3000/api/blogs")
      .then((res) => {
        return res.json();
      })
      .then((data) => {
        console.log(data);
        setBlogs(data);
      });
  }, []);

  return (
    <>
      <Head>
        <title>Blogs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <main className={styles.main}>
          {blogs.map((blog) => {
            return (
              <div className={styles.blogItems} key={`blog-${blog.title}`}>
                <Link
                  href={`/blogpost/${blog.title
                    .trim()
                    .toLowerCase()
                    .split(" ")
                    .join("-")}`}
                >
                  <h3 className={styles.blogTitle}>{blog.title}</h3>
                </Link>
                <p className={styles.blogDesc}>
                  {blog.content.substr(0, 140)}...
                </p>
              </div>
            );
          })}
        </main>
      </div>
    </>
  );
};

export default Blog;
