import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Coder Writes</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h3 className={styles.title}>Coder Writes</h3>

                <p className={styles.description}>A blog for coders by coder</p>

                <div className="blogs">
                    <h2>Popular Blogs</h2>
                    <div className="blogItem">
                        <h1>How to learn JS in 2022</h1>
                        <p>
                            Lorem ipsum, dolor sit amet consectetur adipisicing
                            elit.
                        </p>
                    </div>
                    <div className="blogItem">
                        <h1>How to learn JS in 2022</h1>
                        <p>
                            Lorem ipsum, dolor sit amet consectetur adipisicing
                            elit.
                        </p>
                    </div>
                    <div className="blogItem">
                        <h1>How to learn JS in 2022</h1>
                        <p>
                            Lorem ipsum, dolor sit amet consectetur adipisicing
                            elit.
                        </p>
                    </div>
                    <div className="blogItem">
                        <h1>How to learn JS in 2022</h1>
                        <p>
                            Lorem ipsum, dolor sit amet consectetur adipisicing
                            elit.
                        </p>
                    </div>
                </div>
            </main>
        </div>
    );
}
